# Generated file - do not commit this file.
{
  "name": "design_system",
  "version": "0.0.1",
  "publish_to": "none",
  "environment": {
    "sdk": ">=2.18.1 <3.0.0",
    "flutter": ">=1.17.0"
  },
  "description": "A new Flutter package project.",
  "dependencies": {
    "flutter": {
      "sdk": "flutter"
    },
    "core_module": {
      "path": "C:\\\\flutter-projects\\\\fteam_weather_app\\\\core_module"
    },
    "app_weather": {
      "path": "C:\\\\flutter-projects\\\\fteam_weather_app\\\\app_weather"
    }
  },
  "dev_dependencies": {
    "flutter_test": {
      "sdk": "flutter"
    },
    "flutter_lints": "^2.0.0"
  },
  "dependency_overrides": {
    "app_weather": {
      "path": "..\\\\app_weather"
    },
    "core_module": {
      "path": "..\\\\core_module"
    }
  },
  "flutter": null
}