# Generated file - do not commit this file.
{
  "name": "core_module",
  "version": "0.0.1",
  "publish_to": "none",
  "environment": {
    "sdk": ">=2.18.1 <3.0.0",
    "flutter": ">=1.17.0"
  },
  "description": "A new Flutter package project.",
  "dependencies": {
    "flutter": {
      "sdk": "flutter"
    },
    "bloc": "^8.1.0",
    "flutter_bloc": "^8.0.1",
    "dio": "^4.0.6",
    "flutter_modular": "^5.0.2",
    "google_fonts": "^3.0.1",
    "http": "^0.13.5",
    "mocktail": "^0.3.0",
    "bloc_test": "^9.1.0"
  },
  "dev_dependencies": {
    "test": "any",
    "flutter_test": {
      "sdk": "flutter"
    },
    "flutter_lints": "^2.0.0"
  },
  "flutter": null
}